apiVersion: v1
kind: Service
metadata:
  name: authdemoapi-service
spec:
  selector:
    app: authdemoapi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
